-- La tabla `intereses` nunca se sembró en producción (el catálogo solo vivía
-- en backend/src/config/database.sql, que no forma parte de las migraciones
-- de Prisma). Sin estas filas, GET /api/perfil/intereses devuelve categorias: {}
-- y el selector de intereses de EditarUsuario.jsx aparece vacío.
INSERT INTO "intereses" (nombre, categoria)
SELECT * FROM (VALUES
  ('Gimnasio',              'Deporte y actividad física'),
  ('Yoga',                  'Deporte y actividad física'),
  ('Crossfit',              'Deporte y actividad física'),
  ('Senderismo',            'Deporte y actividad física'),
  ('Dar paseos',            'Deporte y actividad física'),
  ('Ciclismo',              'Deporte y actividad física'),
  ('Running',               'Deporte y actividad física'),
  ('Escalada',              'Deporte y actividad física'),
  ('Natación',              'Deporte y actividad física'),
  ('Fútbol',                'Deporte y actividad física'),
  ('Baloncesto',            'Deporte y actividad física'),
  ('Padel',                 'Deporte y actividad física'),
  ('Artes marciales',       'Deporte y actividad física'),
  ('Surf',                  'Deporte y actividad física'),
  ('Esquí',                 'Deporte y actividad física'),
  ('Vegano',                'Alimentación'),
  ('Vegetariano',           'Alimentación'),
  ('Café de especialidad',  'Alimentación'),
  ('Cocina en casa',        'Alimentación'),
  ('Repostería',            'Alimentación'),
  ('Comida internacional',  'Alimentación'),
  ('Streetfood',            'Alimentación'),
  ('Lectura',               'Cultura y ocio'),
  ('Cine',                  'Cultura y ocio'),
  ('Series',                'Cultura y ocio'),
  ('Teatro',                'Cultura y ocio'),
  ('Música en directo',     'Cultura y ocio'),
  ('Museos',                'Cultura y ocio'),
  ('Fotografía',            'Cultura y ocio'),
  ('Videojuegos',           'Cultura y ocio'),
  ('Podcasts',              'Cultura y ocio'),
  ('Arte',                  'Cultura y ocio'),
  ('Salir de noche',        'Vida social'),
  ('Bares y copas',         'Vida social'),
  ('Viajes',                'Vida social'),
  ('Festivales',            'Vida social'),
  ('Voluntariado',          'Vida social'),
  ('Networking',            'Vida social'),
  ('Salir de tiendas',      'Vida social'),
  ('Miradores',             'Vida social'),
  ('Cafeterías',            'Vida social'),
  ('Meditación',            'Bienestar'),
  ('Pilates',               'Bienestar'),
  ('Vida sostenible',       'Bienestar'),
  ('Mindfulness',           'Bienestar'),
  ('Bienestar mental',      'Bienestar')
) AS v(nombre, categoria)
WHERE NOT EXISTS (SELECT 1 FROM "intereses");
